/**
 * Generate a MeteorSettings interface from the contents of settings.json,
 * so Meteor.settings access can be typed. Pure module, testable outside
 * VS Code.
 */

const INDENT = "    ";
const IDENTIFIER_REGEX = /^[A-Za-z_$][\w$]*$/;

const propertyKey = (key) =>
    IDENTIFIER_REGEX.test(key) ? key : JSON.stringify(key);

const inferType = (value, depth) => {
    if (value === null || value === undefined) return "unknown";

    if (Array.isArray(value)) {
        if (!value.length) return "unknown[]";

        const elementTypes = [
            ...new Set(value.map((element) => inferType(element, depth))),
        ];
        return elementTypes.length === 1
            ? `${elementTypes[0]}[]`
            : `(${elementTypes.join(" | ")})[]`;
    }

    switch (typeof value) {
        case "string":
            return "string";
        case "number":
            return "number";
        case "boolean":
            return "boolean";
        case "object":
            return objectType(value, depth);
        default:
            return "unknown";
    }
};

const objectType = (objectValue, depth) => {
    const entries = Object.entries(objectValue);
    if (!entries.length) return "Record<string, unknown>";

    const padding = INDENT.repeat(depth + 1);
    const lines = entries.map(
        ([key, value]) =>
            `${padding}${propertyKey(key)}: ${inferType(value, depth + 1)};`
    );

    return `{\n${lines.join("\n")}\n${INDENT.repeat(depth)}}`;
};

const generateSettingsTypes = (settings) => {
    return `// Generated by Meteor Impact from settings.json.
// Re-run the "Generate Meteor.settings Types" command after changing settings.json.
//
// Usage:
//     const settings = Meteor.settings as MeteorSettings;

interface MeteorSettings ${objectType(settings || {}, 0)}
`;
};

module.exports = { generateSettingsTypes };
